name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency: ci-${{ github.ref }}

    #env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      #BUNDLE_GEMFILE: ${{ github.workspace }}/ronn-ng/Gemfile

    steps:
      - uses: actions/checkout@v4

      - name: Clone ronn-ng repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'ibokuri'
          repository: 'ronn-ng'

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Make HTML directory
        run: mkdir public

      - name: Build site files
        run: |
          cd ronn-ng
          bundle install --with development
          bundle exec bin/ronn \
            --html \
            --output-dir="../public/" \
            --manual="General Commands Manual" \
            --section=1 \
            --name="phan.computer" \
            ../md/*.md

      - name: Rename HTML files
        run: |
            find public/ -name '*.1.html' -exec sh -c 'mv "$0" "${0%.1.html}.html"' {} \;

      - name: Add CNAME file
        run: echo "phan.computer" > public/CNAME

      - name: Deploy site
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: www
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
