name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: scdoc
          version: 1.11.2-1


      - name: Build
        run: make build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: www
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
